-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 18:44:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

 -- DROP TABLE IF EXISTS `game_company`;
 -- DROP TABLE IF EXISTS `game_company_info`;
 -- DROP TABLE IF EXISTS `game_info`;
 -- DROP TABLE IF EXISTS `game_price`;
 -- DROP TABLE IF EXISTS `genre`;
 -- DROP TABLE IF EXISTS `private_estimate`;
 -- DROP TABLE IF EXISTS `public_estimate`;

-- DROP TABLE IF EXISTS `tmp_data`;
-- -----------------------------------------------------
-- Table `mydb`.`game_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_info` (
  `name` VARCHAR(255) NOT NULL,
  `create_time` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `genre` VARCHAR(15) NOT NULL,
  `game_info_id` INT NOT NULL,
  PRIMARY KEY (`game_info_id`, `genre`),
  CONSTRAINT `fk_genre_game_info`
    FOREIGN KEY (`game_info_id`)
    REFERENCES `mydb`.`game_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`game_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_price` (
  `price` INT UNSIGNED NOT NULL,
  `discounted_price` INT UNSIGNED,
  `dlc_price` INT UNSIGNED DEFAULT 0,
  `game_info_id` INT NOT NULL,
  PRIMARY KEY (`game_info_id`),
  
  CONSTRAINT `check_price_logic`
	CHECK (`discounted_price` <= `price`),
    
  CONSTRAINT `fk_price_game_info1`
    FOREIGN KEY (`game_info_id`)
    REFERENCES `mydb`.`game_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`private_estimate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`private_estimate` (
   -- 1 진행하지 않음, 2 엔딩을 보지 않음, 3 엔딩을 봄, 4 엔딩 이후에 계속함, 5 엔딩이 없는 게임
  `progress` TINYINT NOT NULL,
   -- JSON파일을 통해 값을 집어넣을 경우 0을 인식하지 못함, 데이터 시트에서 0은 NULL로 대체하였음
  `playtime` DECIMAL(7, 1) NOT NULL DEFAULT 0.0,
   -- 1~5 사이 정수형, 0은 평가하지 않음
  `rate` TINYINT NOT NULL DEFAULT 0,
  `game_info_id` INT NOT NULL,
  PRIMARY KEY (`game_info_id`),
  
  CONSTRAINT `check_progress_domain` CHECK (`progress` IN  (1,2,3,4,5)),
  CONSTRAINT `check_rate_domain` CHECK (`rate` IN  (0,1,2,3,4,5)),
    -- 플레이 타임이 0이라면 평가는 0이다.
  CONSTRAINT `check_rate_logic` 
    CHECK ((`playtime` > 0) OR (`rate` = 0)),
    
  CONSTRAINT `fk_private_estimate_game_info1`
    FOREIGN KEY (`game_info_id`)
    REFERENCES `mydb`.`game_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`public_estimate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`public_estimate` (
  `positive_rate` TINYINT, -- 긍정비율 퍼센트 * 100으로 계산
  `HLTB_time` DECIMAL(7, 1) UNSIGNED,
  `rate_amount` INT UNSIGNED,
  `game_info_id` INT NOT NULL,
  PRIMARY KEY (`game_info_id`),
  
  CONSTRAINT `check_positive_rate_domain` CHECK (`positive_rate` BETWEEN 0 AND 100),
  
  CONSTRAINT `fk_public_estimate_game_info1`
    FOREIGN KEY (`game_info_id`)
    REFERENCES `mydb`.`game_info` (`id`)
	ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `mydb`.`game_company_info`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`game_company_info` (
  `name` VARCHAR(63) NOT NULL,
  `country` VARCHAR(31),
  `game_cnt` INT UNSIGNED DEFAULT 1,
  
  PRIMARY KEY (`name`));
  
-- -----------------------------------------------------
-- Table `mydb`.`game_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_company` (
  `game_info_id` INT NOT NULL,
  `company_name` VARCHAR(63) NOT NULL,
  PRIMARY KEY (`game_info_id`),
  CONSTRAINT `fk_bridge_game`
    FOREIGN KEY (`game_info_id`)
    REFERENCES `mydb`.`game_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bridge_company`
    FOREIGN KEY (`company_name`)
    REFERENCES `mydb`.`game_company_info` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);
-- DROP TABLE IF EXISTS `raw_data`;
-- import wizard 같은 조건에서 될 때도 있고 안 될 때도 있음. ???
CREATE TABLE `raw_data` (
    `id` INT,
    `name` VARCHAR(255),
    `create_time` INT,
    `genre(다중값)` VARCHAR(255), 
    `name__1` VARCHAR(255),     
    `country` VARCHAR(255),
    `game_cnt.` INT,         
    `price` INT,
    `discount` INT,
    `dlc_price` INT,
    `progress` INT,
    `playtime` VARCHAR(50),      
    `rate` INT,
    `positive_rate` VARCHAR(50),   
    `HLTB_time` VARCHAR(50),     
    `rate_amount` VARCHAR(50)     
);
-- select * from raw_data;
-- 휴먼에러;;
UPDATE raw_data
SET price = 27000, discount = 10800
WHERE id = 42;
UPDATE raw_data
SET create_time = 230526
WHERE id = 1;
UPDATE raw_data
SET create_time = 240322
WHERE id = 6;

-- 1. 게임 정보 (game_info)
INSERT INTO game_info (name, create_time)
SELECT DISTINCT name, create_time FROM raw_data;

SELECT * FROM game_info;

-- 2. 회사 마스터 정보 (game_company_info)
INSERT INTO game_company_info (name, country, game_cnt)
SELECT DISTINCT `name__1`, country, `game_cnt.`
FROM raw_data
WHERE `name__1` IS NOT NULL;

select * from game_company_info;

-- 3. 게임, 회사 브릿지 연결 (game_company)
INSERT INTO game_company (game_info_id, company_name)
SELECT gi.id, rd.`name__1`
FROM raw_data rd 
JOIN game_info gi ON rd.name = gi.name;

SELECT * FROM game_company;

-- 4. 가격 정보 (game_price)
INSERT INTO game_price (game_info_id, price, discounted_price, dlc_price)
SELECT gi.id, rd.price, rd.discount, rd.dlc_price
FROM raw_data rd 
JOIN game_info gi ON rd.name = gi.name;

SELECT * FROM game_price;

-- 5. 개인 평가 (private_estimate)
UPDATE raw_data -- 빈칸 0으로 채우기
SET playtime = '0' 
WHERE playtime = '';

INSERT INTO private_estimate (game_info_id, progress, playtime, rate)
SELECT gi.id, rd.progress, rd.playtime, rd.rate
FROM raw_data rd 
JOIN game_info gi ON rd.name = gi.name;

SELECT * FROM private_estimate;

-- 6. 대중 평가 (public_estimate)
INSERT INTO public_estimate (game_info_id, positive_rate, HLTB_time, rate_amount)
SELECT 
    gi.id, 
    NULLIF(rd.positive_rate, ''),
    NULLIF(rd.HLTB_time, ''),
    NULLIF(rd.rate_amount, '')
FROM raw_data rd 
JOIN game_info gi ON rd.name = gi.name;

SELECT * FROM public_estimate;

INSERT INTO genre (game_info_id, genre) VALUES
(1, '경영'), (1, '싱글 플레이어'), (1, '시뮬레이션'), (1, '신화'), (1, '샌드박스'), (1, 'RPG'), (1, '무술'),
(2, '앞서 해보기'), (2, '귀여운'), (2, '액션 로그라이크'), (2, '로그라이트'), (2, '액션'),
(3, '액션 로그라이크'), (3, '로그라이트'), (3, '탄막 슈팅'), (3, '약탈 슈팅'), (3, 'RPG'), (3, '전략 RPG'), (3, '로그라이크 덱빌딩'),
(4, 'RPG'), (4, 'JRPG'), (4, '턴제 전투'), (4, '애니메이션'), (4, '풍부한 스토리'), (4, '3D'), (4, '판타지'), (4, '모험'), (4, '시간 관리'),
(5, '귀여운'), (5, '픽셀 그래픽'), (5, '마법'), (5, '시뮬레이션'), (5, '캐주얼'), (5, '퍼즐'),
(6, '턴제 전술'), (6, '복수 결말'), (6, '싱글 플레이어'), (6, '미스터리'), (6, '전술 RPG'), (6, '에니메이션'), (6, '2D'), (6, '전략'),
(7, '무료 플레이'), (7, 'MOBA'), (7, '에니메이션'), (7, 'e스포츠'), (7, 'PvP'), (7, '생존'),
(8, '러브크래프트'), (8, '픽셀 그래픽'), (8, '수사'), (8, 'RPG'), (8, '전략 RPG'), (8, '턴제 전투'), (8, '에니메이션'),
(9, '로그라이크 덱빌딩'), (9, '애니메이션'), (9, 'RPG'), (9, '전략'), (9, '턴제'), (9, '인디'),
(10, '턴제 전투'), (10, '풍부한 스토리'), (10, '판타지'), (10, 'RPG'), (10, 'JRPG'), (10, '탐험'),
(11, '전략'), (11, '전쟁'), (11, '실시간 전략'), (11, '턴제 전략'), (11, '대전략'), (11, '판타지'), (11, 'RTS'), (11, '전술'),
(12, '전략'), (12, '전쟁'), (12, '실시간 전략'), (12, '턴제 전략'), (12, '대전략'), (12, '판타지'), (12, 'RTS'), (12, '전술'),
(13, '전략'), (13, '전쟁'), (13, '실시간 전략'), (13, '턴제 전략'), (13, '대전략'), (13, '판타지'), (13, 'RTS'), (13, '전술'),
(14, '메트로배니아'), (14, '에니메이션'), (14, '귀여운'), (14, '2D 플랫폼'), (14, '탐험'),
(15, 'RPG'), (15, '무술'), (15, '2D'), (15, '복수 결말'), (15, '선택의 중요성'), (15, '깊은 세계관'), (15, '전략'),
(16, '로그라이크 덱빌딩'), (16, '로그라이크'), (16, '턴제 전술'), (16, '육각형 그리드'), (16, '전략'), (16, '카드 게임'),
(17, '귀여운'), (17, '액션'), (17, '인디'), (17, '파괴'), (17, '유머'), (17, '웅장한 사운드트랙'),
(18, '카드 게임'), (18, '로그라이크'), (18, '로그라이크 덱빌딩'), (18, '전략'),
(19, 'RPG'), (19, '캐릭터 커스터마이즈'), (19, '선택의 중요성'), (19, '풍부한 스토리'), (19, '모험'), (19, 'CRPG'), (19, '판타지'), (19, '던전 앤 드래곤'), (19, '턴제 전투'), (19, '전략'),
(20, '전략'), (20, 'RPG'), (20, '중세'), (20, '오픈 월드'), (20, '턴제 전술'), (20, '턴제 전략'),
(21, '탄막 슈팅'), (21, '고난이도'), (21, '슈팅'), (21, '아케이드'), (21, '2D'),
(22, '카드 게임'), (22, '전략'), (22, '덱빌딩'), (22, '인디'), (22, '로그라이트'), (22, '판타지'),
(23, '무료 플레이'), (23, '인디'), (23, '캐주얼'), (23, '액션'), (23, '슈팅'),
(24, '전략'), (24, '인디'), (24, '캐주얼'), (24, '실시간 전략'), (24, '판타지'), (24, '실시간'), (24, '2D'),
(25, '1인칭 슈팅'), (25, '슈팅'), (25, '멀티플레이어'), (25, '경쟁'), (25, '액션'), (25, '팀 기반'),
(26, '전략'), (26, '중세'), (26, '대전략'), (26, '시뮬레이션'), (26, 'RPG'), (26, '역사'), (26, '경영'),
(27, '리듬'), (27, '로그라이크'), (27, '웅장한 사운드트랙'), (27, '픽셀 그래픽'), (27, '인디'),
(28, '기지 건설'), (28, '액션 로그라이크'), (28, '귀여운'), (28, '싱글 플레이어'), (28, '건설'), (28, '로그라이트'), (28, '전략'), (28, '판타지'),
(29, '러브크래프트'), (29, '턴제 전투'), (29, '던전 크롤러'), (29, '로그라이크'), (29, 'RPG'), (29, '인디'), (29, '다크 판타지'),
(30, '공포'), (30, '멀티플레이어'), (30, '생존  공포'), (30, '온라인 협동'), (30, '협동'), (30, '생존'),
(31, '오토 배틀러'), (31, '픽셀 그래픽'), (31, '로그라이크'), (31, '전술'), (31, '인디'), (31, 'RPG'),
(32, '고난이도'), (32, '아케이드'), (32, '2D'), (32, '컨트롤러'), (32, '액션'), (32, '캐주얼'),
(33, '턴제 전술'), (33, '전략 RPG'), (33, '캐릭터 커스터마이즈'), (33, '애니메이션'), (33, '영구적 죽음'), (33, '덱빌딩'),
(34, 'RPG'), (34, '풍부한 스토리'), (34, '선택의 중요성'), (34, '추리'), (34, '아이소메트릭'), (34, 'CRPG'),
(35, '생존'), (35, '멀티플레이어'), (35, '협동'), (35, '오픈 월드'), (35, '모험'), (35, '인디'), (35, '2D'),
(36, 'JRPG'), (36, '전술'), (36, '전략'), (36, '카드 배틀'), (36, '픽셀 그래픽'), (36, '인디'), (36, '판타지'), (36, '애니메이션'),
(37, '액션 로그라이크'), (37, '픽셀 그래픽'), (37, '로그라이트'), (37, '로그라이크'), (37, '인디'), (37, '던전 크롤러'), (37, 'RPG'),
(38, '소울라이크'), (38, '오픈 월드'), (38, '다크 판타지'), (38, 'RPG'), (38, '고난이도'),
(39, '자동화'), (39, '기지 건설'), (39, '자원관리'), (39, '샌드박스'), (39, '크래프팅'), (39, '전략'),
(40, '비주얼 노벨'), (40, '풍부한 스토리'), (40, '애니메이션'), (40, '시간 여행'), (40, '우주'),
(41, '애니메이션'), (41, 'JRPG'), (41, '액션 RPG'), (41, '온라인 협동'), (41, '액션'), (41, 'RPG'),
(42, '턴제 전략'), (42, '전략'), (42, 'RPG'), (42, '싱글 플레이어'), (42, '턴제 전술'), (42, '전술'),
(43, '풍부한 스토리'), (43, '카드 게임'), (43, '전략'), (43, '인디'), (43, '덱빌딩'), (43, '고난이도'),
(44, '풍부한 스토리'), (44, '깊은 세계관'), (44, '턴제 전투'), (44, '무료 플레이'), (44, 'RPG'),
(45, '경영'), (45, '고난이도'), (45, '심리적 공포'), (45, '시뮬레이션'), (45, '풍부한 스토리'),
(46, 'PvE'), (46, '트레이딩 카드 게임'), (46, '턴제 전술'), (46, '카드 배틀'),
(47, '카드 배틀'), (47, '로그라이트'), (47, '카드 게임'), (47, '덱빌딩'), (47, '턴제 전술'),
(48, '무료 플레이'), (48, '카드 게임'), (48, '러브크래프트'), (48, '로그라이크 덱빌딩'),
(49, '카드 배틀'), (49, '덱빌딩'), (49, '로그라이트'), (49, '여주인공'), (49, '턴제 전략'), (49, '3D'),
(50, '무료 플레이'), (50, '웅장한 사운드트랙'), (50, '퍼즐'), (50, '인디'), (50, '빠른 진행'),
(51, '액션 로그라이크'), (51, '고난이도'), (51, '로그라이트'), (51, '덱빌딩'), (51, '카드 배틀'),
(52, '아케이드'), (52, '고난이도'), (52, '릴레싱'), (52, '컨트롤러'), (52, '액션'),
(53, 'RPG'), (53, '어드벤처'), (53, '선택의 중요성'), (53, '턴제 전투'), (53, '판타지'), (53, 'CRPG'), (53, '전략'),
(54, '인디'), (54, '무료 플레이'), (54, '리듬'), (54, '캐주얼'), (54, '액션'), (54, '음악'),
(55, '생존'), (55, '슈팅'), (55, '배틀 로얄'), (55, '멀티플레이어'), (55, '1인칭 슈팅'), (55, 'PVP'),
(56, '협동'), (56, '탄막 슈팅'), (56, '액션 로그라이크'), (56, '귀여운'),
(57, '애니메이션'), (57, '메트로베니아'), (57, '탄막 슈팅'), (57, '여주인공'), (57, '탐험'),
(58, '2D'), (58, '덱빌딩'), (58, '카드 배틀'), (58, '로그라이트'), (58, '전략'), (58, '싱글플레이어'),
(59, '리듬'), (59, '음악'), (59, '고난이도'), (59, '인디'), (59, '아케이드'), (59, '여주인공'), (59, '액션'),
(60, 'RPG'), (60, '텍스트 기반'), (60, '어드벤처'), (60, '인디'), (60, '픽셀 그래픽'), (60, '판타지'),
(61, '아케이드'), (61, '메트로베니아'), (61, '플랫폼'), (61, '액션'), (61, '인디'), (61, '어드벤처'),
(62, '인디'), (62, '액션'), (62, '플랫폼'), (62, '어드벤처'), (62, '고난이도'), (62, '액션 어드벤처'),
(63, '무료 플레이'), (63, '카드 배틀'), (63, '덱빌딩'), (63, '전략'), (63, '트레이딩 카드 게임'), (63, '애니메이션'),
(64, '무료 플레이'), (64, '카드 배틀'), (64, '덱빌딩'), (64, '전략'), (64, '트레이딩 카드 게임'), (64, '애니메이션'),
(65, '전략'), (65, '턴제 전략'), (65, '멀티플레이어'), (65, '역사'), (65, '턴제'), (65, '대전략'),
(66, '로그라이크 덱빌딩'), (66, '카드 게임'), (66, '카드 배틀'), (66, '로그라이크'), (66, '2D'),
(67, '탄막 슈팅'), (67, '아케이드'), (67, 'PvP'), (67, '2D'), (67, '컨트롤러'),
(68, '생존'), (68, '무료 플레이'), (68, 'e스포츠'), (68, '귀여운'),
(69, '비주얼 노벨'), (69, '정치 시뮬레이션'), (69, '정치적'), (69, '자신이 선택하는 모험'),
(70, '전술 RPG'), (70, 'RPG'), (70, '풍부한 스토리'), (70, '턴제 전략'), (70, '판타지'), (70, '2D'),
(71, '메트로베니아'), (71, '에니메이션'), (71, '픽셀 그래픽'), (71, '탄막 슈팅'),
(72, '기지 건설'), (72, '개척 시뮬레이션'), (72, '전략'), (72, '좀비'), (72, '생존'), (72, '도시 건설'),
(73, 'PRG'), (73, 'JRPG'), (73, '픽셀 그래픽'), (73, '인디'), (73, '여주인공'), (73, '애니메이션'),
(74, '전략'), (74, '전술'), (74, '캐릭터 커스터마이즈'), (74, 'RPG'), (74, '턴제 전투'), (74, '영구적 죽음');
SELECT * FROM genre;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;